<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="/resources/styles_new.css"/>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="width: 1080px">

<div class="carousel">
</div>
<div class="pct">
</div>


 <svg   class="Vector1" width="1920" height="254" viewBox="0 0 1920 254" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g filter="url(#filter0_f)">
    <path d="M111.5 120.731V70.8892C123.5 106.445 -76 169.373 -76 129.5C-76 89.6269 145.311 148.672 195.96 165.286L205.507 120.731L324.042 165.286L434.634 36M338.721 63.9644L714.653 165.286V120.731L958.885 165.286V115.444L1217.44 165.286L1273.92 120.731L1456.89 165.286L1546.79 120.731L1749.65 165.286L1707.49 122.619L1953.31 165.286L2009 129.038" stroke="url(#pattern0)" stroke-width="100"/>
  </g>
  <defs>
    <filter id="filter0_f" x="-129" y="0.498535" width="2168.28" height="252.888" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feFlood flood-opacity="0" result="BackgroundImageFix"/>
      <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
      <feGaussianBlur stdDeviation="1.5" result="effect1_foregroundBlur"/>
    </filter>
    <pattern id="pattern0" patternContentUnits="objectBoundingBox" width="1" height="1">
      <use xlink:href="#image0" transform="translate(0 -4.86225) scale(0.00166667 0.0268784)"/>
    </pattern>
    <image id="image0" width="600" height="399" href="cosmos.jpg"/>
  </defs>
</svg>
<svg class="Vector5" width="1920" height="254" viewBox="0 0 1920 254" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g filter="url(#filter0_f)">
    <path d="M111.5 77.4407V70.8892C112.208 72.9867 112.18 75.1795 111.5 77.4407C106.864 92.8614 71.9239 111.469 33.437 124.789C-18.1017 142.626 -76 150.98 -76 129.5C-76 110.381 -25.1166 114.005 33.437 124.789C71.9239 111.469 106.864 92.8614 111.5 77.4407Z" fill="url(#pattern0)"/>
    <path d="M111.5 120.731V70.8892C123.5 106.445 -76 169.373 -76 129.5C-76 89.6269 145.311 148.672 195.96 165.286L205.507 120.731L324.042 165.286L434.634 36M338.721 63.9644L714.653 165.286V120.731L958.885 165.286V115.444L1217.44 165.286L1273.92 120.731L1456.89 165.286L1546.79 120.731L1749.65 165.286L1707.49 122.619L1953.31 165.286L2009 129.038" stroke="url(#pattern1)" stroke-width="100"/>
  </g>
  <defs>
    <filter id="filter0_f" x="-129" y="0.498535" width="2168.28" height="252.888" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feFlood flood-opacity="0" result="BackgroundImageFix"/>
      <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
      <feGaussianBlur stdDeviation="1.5" result="effect1_foregroundBlur"/>
    </filter>
    <pattern id="pattern0" patternContentUnits="objectBoundingBox" width="1" height="1">
      <use xlink:href="#image0" transform="translate(0 -0.564638) scale(0.000260417 0.00419975)"/>
    </pattern>
    <pattern id="pattern1" patternContentUnits="objectBoundingBox" width="1" height="1">
      <use xlink:href="#image1" transform="translate(0 -4.86225) scale(0.00166667 0.0268784)"/>
    </pattern>
    <image id="image0" width="3840" height="507" href="cosmos.jpg"></image>
    <image id="image1" width="600" height="399" href = "cosmos.jpg"></image>
  </defs>
</svg>


<div class="Rectangle1">
</div>
<div class="Rectangle2">
</div>
<div class="Explore">
  Explore
</div>
<div class="Rectangle3">
</div>

<div class="loft">
  Music loft
</div>
<div class="Rectangle5">
</div>

<div class="textt">
  Unlimited possibilities
</div>
<div class="Rectangle4">
</div>
<div class="Disclamer">
  Disclaimer Disclaimer Disclaimer
</div>

</body>
</html>